# lab 5 Al tasks


Lab Tasks

1.	Write a program that inputs a line of text. Output the text in uppercase letters and in lowercase letters using built-in functions.

In [1]:
# Task 1: Convert Text to Uppercase and Lowercase
text = input("Enter a line of text: ")

print("Uppercase:", text.upper())
print("Lowercase:", text.lower())


Enter a line of text:  3


Uppercase: 3
Lowercase: 3



2.	A simple way to estimate the number of words in a string is to count the number of spaces in the string. Write a program that asks the user for a string and returns an estimate of how many words are in the string.




In [2]:
# Task 2: Estimate Number of Words in a String
text = input("Enter a string: ")

# Counting the number of spaces to estimate words
word_count = text.count(" ") + 1

print("Estimated number of words:", word_count)


Enter a string:  4


Estimated number of words: 1


3.	Write a program that asks the user to enter a string s and then converts s to lowercase, removes all the periods and commas from s, and prints the resulting string.(Hint: use the split method)





In [3]:
# Task 3: Convert String to Lowercase and Remove Periods and Commas
s = input("Enter a string: ")

# Convert to lowercase, remove periods and commas
result = s.lower().replace(".", "").replace(",", "")

print("Processed string:", result)


Enter a string:  7


Processed string: 7


4.	A variable ids refers to the list [4353, 2314, 2956, 3382, 9362, 3900]. Using list methods, do the following:
a.	Remove 3382 from the list.
b.	Get the index of 9362.
c.	Insert 4499 in the list after 9362.
d.	Extend the list by adding [5566, 1830] to it.
e.	Reverse the list.
f.	Sort the list.



In [4]:
# Task 4: Manipulating a List
ids = [4353, 2314, 2956, 3382, 9362, 3900]

# a. Remove 3382 from the list
ids.remove(3382)

# b. Get the index of 9362
index_9362 = ids.index(9362)
print(f"Index of 9362: {index_9362}")

# c. Insert 4499 in the list after 9362
ids.insert(index_9362 + 1, 4499)

# d. Extend the list by adding [5566, 1830] to it
ids.extend([5566, 1830])

# e. Reverse the list
ids.reverse()

# f. Sort the list
ids.sort()

print("Final list:", ids)


Index of 9362: 3
Final list: [1830, 2314, 2956, 3900, 4353, 4499, 5566, 9362]


5.	When playing games where you have to roll two dice, it is nice to know the odds of each roll. For instance, the odds of rolling a 12 are about 3%, and the odds of rolling a 7 are about 17%. You can compute these mathematically, but if you don’t know the math, you can write a program to do it. To do this, your program should simulate rolling two dice about 10,000 times and compute and print out the percentage of rolls that come out to be 2, 3, 4, . . . , 12. Print the results in a table format.



In [5]:
import random

# Task 5: Simulate Rolling Two Dice and Compute Odds
rolls = [0] * 13  # Initialize list for counts of each possible roll (2-12)

# Simulate 10,000 rolls of two dice
for _ in range(10000):
    roll = random.randint(1, 6) + random.randint(1, 6)
    rolls[roll] += 1

# Print the results in table format
print("Roll\tProbability")
for i in range(2, 13):
    print(f"{i}\t{rolls[i] / 100:.2f}%")


Roll	Probability
2	2.72%
3	5.42%
4	8.33%
5	11.23%
6	13.29%
7	17.02%
8	14.08%
9	11.30%
10	8.38%
11	5.59%
12	2.64%


6.	Write a function each for mean, median and mode that accepts a list as an argument. The mean, median, and mode functions return an integer.

a.	Using these functions, write a program that generates a 99-element list of random numbers between 1 and 100 (inclusive) and computes its mean, median, mode.


In [6]:
import random
from collections import Counter

# Task 6: Mean, Median, and Mode Functions
def mean(numbers):
    return sum(numbers) / len(numbers)

def median(numbers):
    sorted_numbers = sorted(numbers)
    mid = len(sorted_numbers) // 2
    if len(sorted_numbers) % 2 == 0:
        return (sorted_numbers[mid - 1] + sorted_numbers[mid]) / 2
    else:
        return sorted_numbers[mid]

def mode(numbers):
    counter = Counter(numbers)
    max_count = max(counter.values())
    mode = [k for k, v in counter.items() if v == max_count]
    return mode[0] if len(mode) == 1 else mode

# Generate a list of 99 random numbers between 1 and 100
random_numbers = [random.randint(1, 100) for _ in range(99)]

# Compute and print the mean, median, and mode
print("Mean:", mean(random_numbers))
print("Median:", median(random_numbers))
print("Mode:", mode(random_numbers))


Mean: 50.97979797979798
Median: 53
Mode: [68, 31, 38, 62]



7.	Write a program that rotates the elements of a list so that the element at the first index moves to the second index, the element in the second index moves to the third index, etc., and the element in the last index moves to the first index.



In [7]:
# Task 7: Rotate Elements in a List
def rotate_list(lst):
    return lst[1:] + [lst[0]]

# Example usage
numbers = [1, 2, 3, 4, 5]
rotated_numbers = rotate_list(numbers)
print("Rotated list:", rotated_numbers)


Rotated list: [2, 3, 4, 5, 1]


8.	Write a program that generates 100 random integers that are either 0 or 1. Then find the longest run of zeros, the largest number of zeros in a row. For instance, the longest run of zeros in [1,0,1,1,0,0,0,0,1,0,0] is 4.


In [8]:
import random

# Task 8: Find the Longest Run of Zeros
random_integers = [random.randint(0, 1) for _ in range(100)]
print("Generated list:", random_integers)

max_run = 0
current_run = 0

for number in random_integers:
    if number == 0:
        current_run += 1
        if current_run > max_run:
            max_run = current_run
    else:
        current_run = 0

print("Longest run of zeros:", max_run)


Generated list: [0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0]
Longest run of zeros: 5


9.	Read the size of the matrix from the user. Populate it with data from the user. Print the original ,transpose  and  product of the matrices on the screen.


In [9]:
import numpy as np

# Task 9: Matrix Operations
size = int(input("Enter the size of the matrix: "))

# Populate matrix with user input
matrix = []
print("Enter the matrix values row by row:")
for i in range(size):
    row = list(map(int, input().split()))
    matrix.append(row)

matrix = np.array(matrix)
transpose_matrix = matrix.T
product_matrix = np.dot(matrix, transpose_matrix)

print("Original Matrix:")
print(matrix)

print("Transpose of Matrix:")
print(transpose_matrix)

print("Product of Matrix and its Transpose:")
print(product_matrix)


Enter the size of the matrix:  9


Enter the matrix values row by row:


 3
 5
 4
 2
 6
 0
 8
 6
 5


Original Matrix:
[[3]
 [5]
 [4]
 [2]
 [6]
 [0]
 [8]
 [6]
 [5]]
Transpose of Matrix:
[[3 5 4 2 6 0 8 6 5]]
Product of Matrix and its Transpose:
[[ 9 15 12  6 18  0 24 18 15]
 [15 25 20 10 30  0 40 30 25]
 [12 20 16  8 24  0 32 24 20]
 [ 6 10  8  4 12  0 16 12 10]
 [18 30 24 12 36  0 48 36 30]
 [ 0  0  0  0  0  0  0  0  0]
 [24 40 32 16 48  0 64 48 40]
 [18 30 24 12 36  0 48 36 30]
 [15 25 20 10 30  0 40 30 25]]


--------------------------------THE END-----------------------