# lab 7 All tasks

# Question 1:
Create a 2D NumPy array with dimensions 5x5. Replace all elements in the last column with the mean value of that column.

In [1]:
import numpy as np

# Create a 5x5 NumPy array with random values
array_2d = np.random.randint(1, 101, size=(5, 5))

# Calculate the mean of the last column
mean_last_column = np.mean(array_2d[:, -1])

# Replace all elements in the last column with the mean value
array_2d[:, -1] = mean_last_column

print("Modified array with the last column replaced by the mean value:")
print(array_2d)


Modified array with the last column replaced by the mean value:
[[ 69  74  26  47  41]
 [ 52  33  14  94  41]
 [ 99  56  37  18  41]
 [100  18  41  51  41]
 [ 89  54  78   6  41]]


# Question 2
Create a NumPy array with the numbers 1 to 100. Reshape it into a 10x10 array. Calculate the sum of each row and find the row with the maximum sum.(Hint: you can use 'np.random.randint' to create the 2d array and fill it with random numbers.

In [2]:
import numpy as np

# Create a NumPy array with numbers 1 to 100
array_1d = np.linspace(1, 100, 100)

# Reshape it into a 10x10 array
array_2d = array_1d.reshape(10, 10)

# Calculate the sum of each row
row_sums = np.sum(array_2d, axis=1)

# Find the row with the maximum sum
max_sum_row = np.argmax(row_sums)

print("Array reshaped into 10x10:")
print(array_2d)

print("\nSum of each row:")
print(row_sums)

print("\nRow with the maximum sum (0-indexed):", max_sum_row)


Array reshaped into 10x10:
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]

Sum of each row:
[ 55. 155. 255. 355. 455. 555. 655. 755. 855. 955.]

Row with the maximum sum (0-indexed): 9


---------------------------The end-------------------